trigger:
- main

stages:
- stage: Initialize
  jobs:
  - job: Init
    steps:
    - template: pipelines/initialize_pipeline.yml

- stage: SyncFeature
  dependsOn: Initialize
  jobs:
  - job: SyncFeature
    steps:
    - template: pipelines/sychronizeFeatureBranch_pipeline.yml

- stage: SyncDEV
  dependsOn: SyncFeature
  jobs:
  - job: SyncDEV
    steps:
    - template: pipelines/synchronizeDEV_pipeline.yml
