tenant:
  hostname: "psprod.int-aws-de.webmethods.io"   # webMethodsIO Integration hostname or ip address
  port: "443"                                       # webMethodsIO Integration port
  admin_username: "niveedkumarreddy.bollapally@ibm.com"                     # webMethodsIO Integration user  
  type: "dev"                                         #DEV
