tenant:
  hostname: "psdev.int-aws-de.webmethods.io"   # webMethodsIO Integration hostname or ip address
  port: "443"                                       # webMethodsIO Integration port
  admin_username: "nbol"                     # webMethodsIO Integration user  
  type: "dev"                                         #DEV
